config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf.urls import url
from ads import views
from user import views as userviews

from django_distill import distill_path

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/<int:pk>', userviews.ProfileView.as_view(), name='profile'),
    path('', views.HomePageView.as_view(), name='home'),
    path('<str:category>/<str:slug>', view=views.SubCategoryView.as_view(), name='subcategory'),
    path('<str:category>/<str:subcategory>/<int:pk>', view=views.ClassifiedAdView.as_view(), name='classifiedad'),
    path('new/', view=views.ClassifiedAdViewNew.as_view(success_url='classifiedad_new_success'), name='newad'),
    path('<str:category>/<str:subcategory>/<int:pk>/delete', view=views.ClassifiedAdViewDelete.as_view(), name='deletead'),
    path('<str:category>/<str:subcategory>/<int:pk>/update', view=views.ClassifiedAdViewUpdate.as_view(success_url='classifiedad_update_success'), name='updatead'),
]

ads/models.py
from django.db import models
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from datetime import datetime, timedelta


from taggit.managers import TaggableManager
import django_filters


class Category(models.Model):
    name = models.CharField(default='', max_length=300)
    slug = AutoSlugField(populate_from='name')
    icon = models.ImageField(upload_to='images/icons', default='placeholder.jpg')

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    name = models.CharField(default='', max_length=300)
    slug = AutoSlugField(populate_from='name')
    icon = models.ImageField(upload_to='images/icons', default='placeholder.jpg')
    image = models.ImageField(upload_to='images', default='placeholder.jpg')
    category = models.ForeignKey('Category',
                                 on_delete=models.CASCADE,)

    def __str__(self):
        return self.name


class ClassifiedAd(models.Model):
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    modified = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(User,
                                on_delete=models.CASCADE,
                                default=0)
    name = models.CharField(default='', max_length=300)
    slug = AutoSlugField(populate_from='name')
    transaction_type = models.CharField(default='unspecified', max_length=20)
    price = models.IntegerField(default=0)
    description = models.TextField(default='')
    views = models.IntegerField(default=0)
    lifetime = models.IntegerField(default=14)
    subcategory = models.ForeignKey('SubCategory',
                                    on_delete=models.CASCADE,)
    tags = TaggableManager()

    def __str__(self):
        return self.name

    @property
    def is_expired(self):
        if datetime.now() >= (self.created + timedelta(days=self.lifetime)):
            return True
        return False

    @property
    def will_expire(self):
        return self.created + timedelta(days=self.lifetime)

    @staticmethod
    def _bootstrap(locale='et'):
        from mimesis import Generic
        from user.models import _generate_fake_user
        import random
        g = Generic(locale)

        fail_image = None
        fail_image_second = None

        for _ in range(0, 22):
            cat = Category()
            cat.name = g.text.word().title()
            cat.icon = random.choice(['fa-ad', 'fa-accessible-icon', 'fa-accusoft', 'fa-adn', 'fa-american-sign-language-interpreting', 'fa-apple-alt'])
            cat.save()
            for _ in range(0, random.randint(2, 10)):
                sub = SubCategory()
                sub.name = g.text.word().title()
                sub.category = cat
                sub.icon = random.choice(['fa-ad', 'fa-accessible-icon', 'fa-accusoft', 'fa-adn', 'fa-american-sign-language-interpreting', 'fa-apple-alt'])
                try:
                    sub.image = g.internet.stock_image(200, 200, ['buy', 'sell', 'rent'])
                    fail_image = sub.image
                except:
                    sub.image = fail_image
                sub.save()
                for _ in range(0, random.randint(10, 50)):
                    ad = ClassifiedAd()
                    ad.subcategory = sub
                    ad.name = g.text.word().title()
                    ad.creator = _generate_fake_user()
                    ad.description = g.text.text()
                    ad.transaction_type = random.choice(['Ost', 'Müük', 'Rent', 'Tutvus'])
                    ad.lifetime = g.numbers.between(3, 35)
                    ad.price = g.numbers.between(1, 500000)
                    ad.views = g.numbers.between(1, 7000)
                    ad.save()
                    for _ in range(0, random.randint(2, 4)):
                        images = ClassifiedAdImage()
                        images.associated_ad = ad
                        try:
                            images.image = g.internet.stock_image(600, 600)
                            fail_image_second = images.image
                        except:
                            images.image = fail_image_second

                        images.save()


class ClassifiedAdImage(models.Model):
    image = models.ImageField(default='placeholder.jpg')
    associated_ad = models.ForeignKey('ClassifiedAd',
                                      on_delete=models.CASCADE,
                                      related_name='images')


class ClassifiedAdFilter(django_filters.FilterSet):
    name = django_filters.CharFilter(lookup_expr='iexact')

    class Meta:
        model = ClassifiedAd
        fields = {'name': [],
                  'created': [],
                  'transaction_type': [],
                  'price': ['lt', 'gt']
                  }

user/models.py
from django.db import models
from django.contrib.auth.models import User
from mimesis import Person


def _generate_fake_user(locale='et'):
    g = Person(locale)
    fake = User()
    fake.username = g.username()
    fake.first_name = g.surname()
    fake.last_name = g.last_name()
    fake.email = g.email()
    fake.save()
    return User.objects.get(username=fake.username)

ads/views.py
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from ads.models import Category, SubCategory, ClassifiedAd
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
class HomePageView(ListView):
    template_name = "ads/home.html"
    model = Category


class SubCategoryView(DetailView):
    template_name = "ads/subcategory.html"
    model = SubCategory


class ClassifiedAdView(DetailView):
    template_name = "ads/classifiedad.html"
    model = ClassifiedAd


class ClassifiedAdViewNew(CreateView, LoginRequiredMixin):
    template_name = "ads/classifiedad_add.html"
    model = ClassifiedAd
    fields = ['name', 'transaction_type', 'price', 'description', 'subcategory', ]


class ClassifiedAdViewDelete(DeleteView, LoginRequiredMixin):
    template_name = "ads/classifiedad_delete.html"
    model = ClassifiedAd
    fields = ['name', 'transaction_type', 'price', 'description', 'subcategory', ]


class ClassifiedAdViewUpdate(UpdateView, LoginRequiredMixin):
    template_name = "ads/classifiedad_update.html"
    model = ClassifiedAd
    fields = ['name', 'transaction_type', 'price', 'description', 'subcategory', ]

user/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.views.generic import DetailView


class ProfileView(LoginRequiredMixin, DetailView):
    template_name = 'profile.html'
    model = User

ads/templates/ads/classifiedad.html
{% extends "base.html" %}
{% load static i18n%}

{% block css %}
     <link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"
   integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
   crossorigin=""/>
{% endblock css %}

{% block content %}
    <div class="container-fluid" id="ad">
        <main class="col-12 py-md-3 pl-md-5">
            <div class="row pb-5">

                <h1 class="mx-auto">
                    <span class="badge badge-primary bg-2">{{ classifiedad.transaction_type }}</span>
                    <small>{{ classifiedad.name }}</small>
                </h1>
            </div>
            <div class="row pb-5">
                <div class="col-1 move-buttons">
                    {% if classifiedad.get_previous_by_created %}
                    <a href="{% url 'classifiedad' pk=classifiedad.get_previous_by_created.pk subcategory=classifiedad.get_previous_by_created.subcategory category=classifiedad.get_previous_by_created.subcategory.category %}">
                        <img src="{% static 'icons/back.svg' %}" alt="next" class="max-w-100 ad-move-buttons">
                    </a>
                    {% endif %}
                </div>
                <div class="col-2 ml-md-auto">
                    {% for image in classifiedad.images.all|slice:":3" %}
                        <img src="{{ image.image }}" alt="" style="width: 100px" class="rounded float-right m-3 img-thumbnail fade-in">
                    {% endfor %}
                </div>
                <div class="col-4 ml-md-auto">
                    <a href="#exampleModalCenter" role="button" data-toggle="modal">
                        <img src="{{ classifiedad.images.first.image }}" alt="" style="width: 500px" class="rounded rounded mx-auto d-block img-fluid fade-in" id="img-hero">
                    </a>
                </div>

                <div class="col-3 fade-in">
                    <div class="row">
                        <div class="col-3">
                        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                          <a class="nav-link active ad-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-location" role="tab" aria-controls="v-pills-messages" aria-selected="false">Asukoht</a>
                          <a class="nav-link ad-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">Kontakt</a>
                          <a class="nav-link ad-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">Metainfo</a>
                        </div>
                        </div>
                        <div class="col-9">
                        <div class="tab-content" id="v-pills-tabContent">
                          <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
                              <div class="col-12 ml-3">
                                  <p>
                                  <span class="badge badge-primary">Telefon:</span><br>
                                      <small>563452243</small>
                                  </p>
                                  <p>
                                  <span class="badge badge-primary">Email:</span><br>
                                      <small>kass@pass.ee</small>
                                  </p>

                              </div>
                          </div>
                          <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
                              <div class="col-12 ml-3">
                                  <p>
                                  <span class="badge badge-primary">Loodud:</span><br>
                                      <small>{{ classifiedad.created|timesince }} ago</small>
                                  </p>
                                  {% if  classifiedad.modified != classifiedad.created %}
                                      <p>
                                      <span class="badge badge-primary">Muudetud:</span><br>
                                          <small>{{ classifiedad.modified|timesince }} ago</small>
                                      </p>
                                  {% endif %}
                                  <p>
                                  <span class="badge badge-primary">Vaatamisi:</span><br>
                                      <small>{{ classifiedad.views }}</small>
                                  </p>
                              </div>
                          </div>
                          <div class="tab-pane fade show active" id="v-pills-location" role="tabpanel" aria-labelledby="v-pills-messages-tab">
                              <div class="col-12 ml-3">
                                <span class="badge badge-primary">Linn:</span><br>
                                  <small>Tartu</small><br>
                                <span class="badge badge-primary">Kaart:</span><br>
                                <div id="mapid" class="mt-1"></div>
                              </div>
                          </div>
                        </div>
                        </div>
                        </div>
                </div>
                <div class="col-1 move-buttons">
                    {% if classifiedad.get_next_by_created %}
                    <a href="{% url 'classifiedad' pk=classifiedad.get_next_by_created.pk subcategory=classifiedad.get_next_by_created.subcategory category=classifiedad.get_next_by_created.subcategory.category %}">
                        <img src="{% static 'icons/next.svg' %}" alt="next" class="max-w-100 ad-move-buttons">
                    </a>
                    {% endif %}
                </div>
            </div>
            <div class="row col-3 mx-auto mb-3">
                <div class="mx-auto ad-price">Hind: {{ classifiedad.price }} eur</div>
            </div>
            <div class="row col-10 mx-auto">
                <p>{{ classifiedad.description }}</p>
            </div>
            <div class="row ">
                <h4 class="mx-auto">Sarnased kuulutused</h4>
            </div>
            <div class="row">
                {% for similar_object in  classifiedad.tags.similar_objects %}
                    <div class="col-2 ml-md-auto">
                        <img src="{{ similar_object.image }}" alt="" style="width: 100px" class="rounded float-right m-3 img-thumbnail">
                    </div>
                {% endfor %}
            </div>

        </main>
    </div>
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">

            <img src="{{ classifiedad.images.first.image }}" alt="" style="width: 900px" class="rounded rounded mx-auto d-block img-fluid" id="img-modal">

        </div>
      </div>
    </div>
{% endblock content %}

{% block javascript %}
    <script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
       integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
       crossorigin="">
    </script>
    <script type="text/javascript">
        var mymap = L.map('mapid').setView([51.505, -0.09], 13);
        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        maxZoom: 18,
        id: 'mapbox.streets',
        accessToken: 'your.mapbox.access.token'
        }).addTo(mymap);
    </script>
    <script type="text/javascript">
        $(document).ready(function(){
            $(".img-thumbnail").click(
                function() {
                    $("#img-hero").attr("src", $(this).attr("src"));
                    $("#img-modal").attr("src", $(this).attr("src"));
                    $(".img-thumbnail").removeClass("active-thumb");
                    $(this).addClass("active-thumb");
                },);
        });
    </script>

{% endblock javascript %}

ads/templates/ads/classifiedad_add.html
{% extends "base.html" %}
{% block content %}
    <form method="post">
    {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Postita">
    </form>
{% endblock content %}

ads/templates/ads/classifiedad_delete.html
{% extends "base.html" %}
{% block content %}
    <form method="post">
    {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Kinnita">
    </form>
{% endblock content %}

ads/templates/ads/classifiedad_delete_success.html
{% extends "base.html" %}
{% block content %}
    Kuulutus kustutatud
{% endblock content %}

ads/templates/ads/classifiedad_update.html
{% extends "base.html" %}
{% block content %}
    <form method="post">
    {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Uuenda">
    </form>
{% endblock content %}

ads/templates/ads/home.html
{% extends "base.html" %}
{% block content %}
    <div class="container-fluid">
        <div class="row flex-xl-nowrap">
            <div class="col-12 py-md-3 pl-md-5 cat-cloud">
                <p>
                    {% for category in category_list %}
                        <a class="badge badge-info" href="#{{ category|slugify }}"><i class="fab {{ category.icon }}"></i> {{ category }}</a>
                    {% endfor %}
                </p>
            </div>
        </div>
        <div class="row flex-xl-nowrap">
            <main class="col-12 py-md-3 pl-md-5">
                {% for category in category_list %}
                    <div class="p-3">
                    <div class="cat-name" id="{{ category|slugify }}"><i class="fab {{ category.icon }} "></i> {{ category }}</div>
                    <div class="row cat-items">
                    {% for subcategory in category.subcategory_set.all %}
                        <a class="title-link" href="{% url 'subcategory' category=category.slug slug=subcategory.slug %}">
                        <div class="card bg-dark text-white m-3 home-item-card">
                          <img src="{{ subcategory.image }}" class="card-img" alt="..." width="200px">
                          <div class="card-img-overlay">
                            <div class="card-title mt-4 title">{{ subcategory.name }}</div>
                          </div>
                          <small class="title-count">{{ subcategory.classifiedad_set.count }} kuulutust</small>
                        </div>
                        </a>
                    {% endfor %}
                    </div>
                    </div>
                {% endfor %}
            </main>
        </div>
  </div>
{% endblock content %}
{% block javascript %}

{% endblock javascript %}

ads/templates/ads/subcategory.html
{% extends "base.html" %}
{% block content %}
    <div class="container-fluid">
        <main class="col-12 py-md-3 pl-md-5">
            <div class="breadcrumb2"><a href="{% url 'home' %}">Esileht</a> <i class="fas fa-long-arrow-alt-right"></i>
                <a href="{% url 'subcategory' category=subcategory.category.slug slug=subcategory.slug %}">{{ subcategory.category }}</a>
                <i class="fas fa-long-arrow-alt-right"></i> {{ subcategory }}</div>
            <div class="row mb-3 mt-3">
                <div class="btn-group ml-3">
                    <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                        Filter
                    </button>
                    <div class="dropdown-menu">
                        <form method="GET">
                            <input type="submit" name="ordeing" value="Odavamad enne" class="dropdown-item">
                        </form>
                        <form method="GET">
                            <input type="submit" name="ordeing" value="Kallimad enne" class="dropdown-item">
                        </form>
                    </div>
                </div>
                <div class="btn-group ml-3">
                    <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                        Kategooriad
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Separated link</a>
                    </div>
                </div>
                <div class="input-group col-2 col-sm-5 col-md-3 col-lg-3 col-xl-3">
                    <div class="input-group-prepend ml-1">
                        <span class="input-group-text">Hind</span>
                    </div>
                    <input type="number" aria-label="Low" class="form-control">
                    <input type="number" aria-label="High" class="form-control">
                    <div class="input-group-append">
                        <span class="input-group-text">€</span>
                    </div>
                </div>

            </div>
            <div class="row">
                {% for ad in subcategory.classifiedad_set.all %}
                    <a href="{% url 'classifiedad' pk=ad.pk subcategory=ad.subcategory.slug category=ad.subcategory.category.slug %}">
                        <div class="card item-card bg-dark text-white m-3" id="ad">
                            <img src="{{ ad.images.first.image }}" class="card-img" alt="...">
                            <div class="card-img-overlay ">
                                <div class="card-title mt-3 title font-weight-normal">{{ ad.name }}</div>
                                <p class="ad-description">{{ ad.description |truncatewords:20 }}</p>
                            </div>
                            <div class="mx-auto">
                                <span class="badge badge-pill badge-info m-1">{{ ad.transaction_type }}</span>
                                <span class="badge badge-pill badge-success m-1">€ {{ ad.price }}</span>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </main>
    </div>
{% endblock content %}

templates/base.html
{% load static i18n%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
    {% block css %}
    {% endblock css %}
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

</head>
<body>

<main>
    <nav class="navbar navbar-expand-sm navbar-light justify-content-between bottom-border" id="top">
        <a class="navbar-brand icon" href="{% url 'home' %}">
            <img src="{% static 'icons/wall.svg' %}">
            <span id="nav-title">Sein</span>
        </a>
        <div class="">
            <a href="">
                <button type="button" class="btn btn-outline-primary"><i class="fas fa-plus"></i> Lisa</button>
            </a>
        </div>

        <div class="input-group col-6">
          <input type="text" class="form-control" placeholder="Näiteks: Korter" aria-label="Recipient's username" aria-describedby="basic-addon2">
          <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button"><i class="fas fa-times"></i></button>
          </div>
          <div class="input-group-append">
            <button class="btn btn-outline-success" type="button">Otsi</button>
          </div>

        </div>

        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link text-secondary" href="{% url 'login' %}">Logi Sisse</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-secondary" href="{% url 'django_registration_register' %}">Registreeru</a>
            </li>
        </ul>
    </nav>


    {% if messages %}
    {% for message in messages %}
    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
    {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock content %}
    <a href="#top"><button type="button" class="btn btn-warning jump-up"><i class="fas fa-caret-up"></i></button></a>

</main>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js" integrity="sha384-7aThvCh9TypR7fIc2HV4O/nFMVCBwyIUKL8XCtKE+8xgCgl/PQGuFsvShjr74PBp" crossorigin="anonymous"></script>
    {% block javascript %}
    {% endblock javascript %}
</body>
</html>

user/templates/django_registration/activation_complete.html
{% extends "base.html" %}
{% block content %}
    Aktiveerimine õnnestus!
{% endblock content %}

user/templates/django_registration/activation_failed.html
{% extends "base.html" %}
{% block content %}
    Aktiveerimine ebaõnnestus!
{% endblock content %}

user/templates/django_registration/registration_complete.html
{% extends "base.html" %}
{% block content %}
    Registreerimine õnnestus!
{% endblock content %}

user/templates/django_registration/registration_form.html
{% extends "base.html" %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
        <div class="col-3"></div>
        <form method="post" class="p-3 m-5 col-6 card">
        {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Registreeru">
        </form>
    </div>
    </div>
{% endblock content %}

user/templates/profile.html
{% extends "base.html" %}
{% block content %}
    <h2>Name:</h2>
    {{ user.username }}
    <h2>Joined:</h2>
    {{ user.date_joined }}
    <h2>Last logged in:</h2>
    {{ user.last_login }}
    <h2>Activated:</h2>
    {{ user.is_active }}
    <h2>Staff:</h2>
    {{ user.is_staff }}
    <h3>Kuulutused:</h3>
    <ul>
    {% for ad in user.classifiedad_set.all %}
        <li>
            <a href="{% url 'classifiedad' pk=ad.pk subcategory=ad.subcategory category=ad.subcategory.category %}">
                {{ ad.name }}
            </a> - Loodud: {{ ad.created }} - Aegub: {{ ad.will_expire }}
            <a href="{% url 'updatead' pk=ad.pk subcategory=ad.subcategory category=ad.subcategory.category %}"><button>Uuenda</button></a>
            <a href="{% url 'deletead' pk=ad.pk subcategory=ad.subcategory category=ad.subcategory.category %}"><button>Kustuta</button></a>
        </li>
    {% endfor %}
    </ul>
{% endblock content %}